version: '2'

services:
  app:
    image: 'social-api:1.0.0'
    build:
      context: .
    ports:
      - "8081:8081"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/social
      - SPRING_DATASOURCE_USERNAME=james
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=james
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=social